### ISSUE TITLE
support all platform?

### ISSUE THREAD

**Issue by ikvm** [CoreForms/MigrationSupport#1]
it run only .net6/.net7/.net8 windows,  Is there a plan to support all platform?

**Comment by MichaelKetting** [comment]
Hi @ikvm, thanks for the question!

We do have a plan on what is required to remove the Windows dependency and make it run on Linux (and I would assume macOS). Actually implementing it requires enough interest to make it a valid business case. Please send us an inquiry via https://coreforms.net/#contact and our product manager will get in touch. 

I'll close this now as an answered question. Feel free to add more comments if you need more details!

Michael
